package com.bhf.fieldvalidation;

import com.bht.md.messages.MarketState;
import com.bht.md.messages.QuoteCondition;
import com.bht.md.messages.QuoteSide;

/**
 * A sample field value validator for a single sided quote with
 * 2 different styles of validating. The first one should inline
 * but just incase, there is a final nested version which should
 * be eligible for aggressive inlining. The generated bytecode
 * of the second version is also half the size, but still bigger than 35 bytes
 * so could be further split down if needed.
 * This also depends on your MaxInlineSize, whether the method becomes hot etc
 *
 * This style of validation does not offer any feedback in terms
 * of which field is not valid. It's more appropriate if you don't care
 * why validation failed, it just did. It also requires you have
 * all field values you want to check in advance of doing the validation.
 */
public class CombinedFieldValidatorStyle {

    private static final short MAX_SYMB_VALUE = 254;

    public boolean isValid(
            long time,
            short symb,
            MarketState marketstate_,
            QuoteCondition quotecondition_,
            long quote_price,
            long quote_qty,
            QuoteSide quote_side) {

        boolean isValid = true;

        isValid &= time > 0;

        // symb is a good example of an edge case where the
        // max and min values of the Java type don't match of the SBE type
        isValid &= symb > 0 && symb < MAX_SYMB_VALUE;
        isValid &= null != marketstate_;
        isValid &= null != quotecondition_;
        isValid &= quote_price > 0;
        isValid &= quote_qty > 0;
        isValid &= null != quote_side;

        return isValid;
    }

    public final boolean isValidShort(
            long time,
            short symb,
            MarketState marketstate_,
            QuoteCondition quotecondition_,
            long quote_price,
            long quote_qty,
            QuoteSide quote_side) {
        return time > 0
                && symb > 0
                && symb < MAX_SYMB_VALUE
                && null != marketstate_
                && null != quotecondition_
                && quote_price > 0
                && quote_qty > 0
                && null != quote_side;
    }
}
